ALTER TABLE prescriptions 
  MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY dispensed_at TIMESTAMP NULL DEFAULT NULL,
  MODIFY patient_id INT NOT NULL,
  MODIFY created_by INT NOT NULL,
  MODIFY route VARCHAR(50) NOT NULL DEFAULT 'Oral'; 